version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro